name: Python Backend Test
on: 
  push: 
    branches: 
      - main
      - development
      - feature/ptests-backend
  pull_request:
    branches:
      - main
      - development
      - feature/ptests-backend
  

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ACS_API_KEY: ${{ secrets.ACS_API_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # or '3.13' if you need it
          cache: 'pip'  # Caches pip dependencies for faster builds
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        working-directory: ./backend
        run: pytest
