name: Python Backend Test
on: 
  push: 
    branches: 
      - main
      - development
      - feature/ptests-backend
  pull_request:
    branches:
      - main
      - development
      - feature/ptests-backend
  

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      SUMO_LOGIC_URL: ${{ secrets.SUMO_LOGIC_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ACS_API_KEY: ${{ secrets.ACS_API_KEY }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.17"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          uv sync --locked

      - name: Create symlink for ml directory
        working-directory: ./backend
        run: |
          ln -s ../ml ./ml

      - name: Run tests
        working-directory: ./backend
        run: |
          uv run pytest tests/ -v
